<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iOQRjul' shared service.

return $this->privates['.service_locator.iOQRjul'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\RoomController::show' => ['privates', '.service_locator.BkOHXLl', 'get_ServiceLocator_BkOHXLlService.php', true],
    'App\\Controller\\RoomController:show' => ['privates', '.service_locator.BkOHXLl', 'get_ServiceLocator_BkOHXLlService.php', true],
], [
    'App\\Controller\\RoomController::show' => '?',
    'App\\Controller\\RoomController:show' => '?',
]);
