<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBx8Lju1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBx8Lju1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBx8Lju1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBx8Lju1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBx8Lju1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Bx8Lju1',
    'container.build_id' => '93a26c8e',
    'container.build_time' => 1572001575,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBx8Lju1');
